name: Java CI

on: [push]

jobs:
  compileJava:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Compile project
      run: |
        chmod +x ./gradlew
        ./gradlew compileJava
